export const REQUEST_REDDIT_POSTS = 'REQUEST_REDDIT_POSTS';
export const RECEIVE_REDDIT_POSTS = 'RECEIVE_REDDIT_POSTS';
// export const HIDE_REDDIT_POST = 'HIDE_REDDIT_POST';
// export const ADD_REDDIT_POST = 'ADD_REDDIT_POST';
